name: tools-modified
description: Tools modified

inputs:
  tools-dir:
    description: 'The  name of the directory that contains tools.'
    required: true
    default: 'tools'
outputs:
  tools-modified:
    description: "The list of tools that have changed"
    value: ${{ steps.check-modified.outputs.tools_modified }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: check-modified
      id: check-modified
      run: |
        echo "tools_modified=$(git diff --name-only -r HEAD^1 HEAD | grep "^$TOOLS_DIR/" | cut -d'/' -f2 | sort | uniq)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TOOLS_DIR: ${{ inputs.tools-dir }}
