name: Create Docker Images
run-name: ${{ gitea.actor }} is is running Create Docker Images


on:
  push:
    branches:
        - "master"
        - "main"
        - "issue**"
        - "WORK**"
  pull_request:


env:
  EXTERNAL_REGISTRY: "docker.io"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build # on always
        env:
          CI_JOB_STAGE: build
        run: |
          bash -x pipeline/pipeline-entry.sh
      - name: test # on always
        env:
          CI_JOB_STAGE: test
        run: |
          bash -x pipeline/pipeline-entry.sh
      - name: deploy # on always
        env:
          CI_JOB_STAGE: deploy
          DOCKER_IO_USER: ${{ secrets.DOCKER_IO_USER }}
          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
          EXTERNAL_REGISTRY: ${{ secrets.EXTERNAL_REGISTRY }}
        run: |
          bash -x pipeline/pipeline-entry.sh
