name: Create Docker Images
run-name: ${{ gitea.actor }} is is running Create Docker Images


on:
  push:
    branches:
        - "master"
        - "issue**"

env:
  EXTERNAL_REGISTRY: "docker.io"

jobs:
  init:
    runs-on: default
    outputs:
      tools-changed: ${{ steps.tools-changed.output.tools-changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tools-changed
        uses: tools-changed
        with:
          tools-dir: tools
  build:
    runs-on: default
    needs:
      - init
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build # on always
        uses: docker-build
        with:
          stage: build
          tools-dir: tools
          tools-modified: ${{needs.init.outputs.tools-modified}}
          build-version: ${{github.ref_name}}
  test:
    runs-on: default
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test # on always
        uses: docker-build
        with:
          stage: test
          tools-dir: tools
          tools-modified: ${{needs.init.outputs.tools-modified}}
          build-version: ${{github.ref_name}}
  deploy:
    runs-on: default
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy # on always
        uses: docker-build
        with:
          stage: deploy
          tools-dir: tools
          tools-modified: ${{needs.init.outputs.tools-modified}}
          build-version: ${{github.ref_name}}
