name: check-modified
description: 'Check for modified genomic tools'

on:
  workflow-call:
    inputs:
      tools-dir:
        description: 'The  name of the directory that contains tools.'
        required: true
        default: 'tools'
    outputs:
      tools-modified:
        description: "The list of tools that have changed"
        value: ${{ jobs.get-modified.outputs.tools_modified }}

jobs:
  get-modified:
    name: get-modified
    runs-on: default
    outputs:
      tools_modified: ${{ steps.check-modified.outputs.tools_modified }}
    steps:
      - name: check-modified
        id: check-modified
        run: |
          echo "tools_modified=$(git diff --name-only -r HEAD^1 HEAD | grep "^$TOOLS_DIR/" | cut -d'/' -f2 | sort | uniq)" >> $GITHUB_OUTPUT
        shell: bash
        env:
          TOOLS_DIR: ${{ inputs.tools-dir }}
