name: Create Docker Images
run-name: ${{ github.actor }} is is running Create Docker Images


on:
  push:
    branches:
        - "master"
        - "main"
        - "issue**"
        - "WORK**"
  pull_request:


env:
  EXTERNAL_REGISTRY: "docker.io"


jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tools_modified: ${{ steps.get-tools-modified.outputs.tools-modified }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get-tools-modified
        id: get-tools-modified
        uses: /home/runner/work/genomics-tools/.github/workflows/tools-modified
        with:
          tools-dir: tools
  build:
    runs-on: ubuntu-latest
    needs:
      - init
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build # on always
        uses: ./.github/workflows/docker-build
        with:
          stage: build
          tools-dir: tools
          tools-modified: ${{needs.init.outputs.tools_modified}}
          build-version: ${{github.ref_name}}
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test # on always
        uses: ./.github/workflows/docker-build
        with:
          stage: test
          tools-dir: tools
          tools-modified: ${{needs.init.outputs.tools_modified}}
          build-version: ${{github.ref_name}}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy # on always
        uses: ./.github/workflows/docker-build
        with:
          stage: deploy
          tools-dir: tools
          tools-modified: ${{needs.init.outputs.tools_modified}}
          build-version: ${{github.ref_name}}
